import { NgModule } from "@angular/core";
import {
  MatTableModule,
  MatStepperModule,
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatOptionModule,
  MatSelectModule,
  MatIconModule,
  MatPaginatorModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatDividerModule,
  MatGridListModule,
  MatCheckboxModule,
  MatRadioModule,
  MatSortModule,
  MatTabsModule,
  MatProgressSpinnerModule,
  MatMenuModule,
  MatAutocompleteModule,
  MatCardModule,
  MatChipsModule,
  MatListModule,
  MatDialogModule,
  MatExpansionModule,
  MatTooltipModule,
  MatBadgeModule,
  MatBottomSheetModule
} from "@angular/material";
 
@NgModule({
  exports: [
    MatTableModule,
    MatStepperModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatOptionModule,
    MatSelectModule,
    MatDatepickerModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatDividerModule,
    MatGridListModule,
    MatCheckboxModule,
    MatRadioModule,
    MatSortModule,
    MatTabsModule,
    MatMenuModule,
    MatAutocompleteModule,
    MatCardModule,
    MatChipsModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatExpansionModule,
    MatTooltipModule,
    MatBadgeModule,
    MatBottomSheetModule
  ]
})
export class MaterialModule {}